[package]
name = "DSNScanner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
ipnetwork = "0.20"
trust-dns-client = "0.23"
futures = "0.3"
